class CatType {
  int id;
  String name;
  String description;
  String tagline;
  int sortOrder;
  String imageName;
  double percentMatch;
  List<StatValue> stats;

  CatType(
      this.id,
      this.name,
      this.description,
      this.tagline,
      this.sortOrder,
      this.imageName,
      this.percentMatch,
      this.stats);
}

class StatValue {
  String name;
  bool isPercent;
  double value;
  StatValue(this.name, this.isPercent, this.value);
}

List<CatType> catType = [
  // 1–5 values: Energy, Playfulness, Affection, Independence, Sociability,
  //             Vocality, Confidence, Sensitivity, Adaptability, Intelligence

  CatType(1,
    'Professional Napper',
      'A calm, low-energy cat who loves sleeping and relaxing most of the day.',
      'Sleep first, everything else later.',
      1, 'Professional_Napper', 1.0, [
    StatValue('Energy Level', false, 1),
    StatValue('Playfulness', false, 1),
    StatValue('Affection Level', false, 2),
    StatValue('Independence', false, 5),
    StatValue('Sociability', false, 2),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 2),
  ]),

  CatType(2, 'Lap Legend',
      'A devoted cuddle companion who loves sitting on laps and being close to people.',
      'Your lap is home.',
      2, 'Lap_Legend', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 2),
    StatValue('Affection Level', false, 5),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 4),
    StatValue('Vocality', false, 2),
    StatValue('Confidence', false, 3),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(3, 'Zen Companion',
      'An easygoing, peaceful cat that adapts well to calm homes and routines.',
      'Calm vibes only.',
      3, 'Zen_Companion', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 2),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 4),
    StatValue('Sociability', false, 3),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 5),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(4, 'Old Soul',
      'A mature, thoughtful cat with a steady temperament and gentle presence.',
      'Wise beyond their whiskers.',
      4, 'Old_Soul', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 2),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 4),
    StatValue('Sociability', false, 2),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 5),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(5, 'Quiet Shadow',
      'A low-profile cat who stays nearby without demanding attention.',
      'Always near, never loud.',
      5, 'Quiet_Shadow', 1.0, [
    StatValue('Energy Level', false, 1),
    StatValue('Playfulness', false, 1),
    StatValue('Affection Level', false, 2),
    StatValue('Independence', false, 4),
    StatValue('Sociability', false, 1),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 3),
    StatValue('Sensitivity', false, 3),
    StatValue('Adaptability', false, 2),
    StatValue('Intelligence', false, 2),
  ]),

  CatType(6, 'Zoomie Rocket',
      'A high-energy cat who loves running, jumping, and nonstop movement.',
      'Fueled by pure chaos.',
      6, 'Zoomie_Rocket', 1.0, [
    StatValue('Energy Level', false, 5),
    StatValue('Playfulness', false, 5),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 4),
    StatValue('Vocality', false, 3),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(7, 'Parkour Cat',
      'An athletic climber who turns furniture into an obstacle course.',
      'The floor is optional.',
      7, 'Parkour_Cat', 1.0, [
    StatValue('Energy Level', false, 5),
    StatValue('Playfulness', false, 4),
    StatValue('Affection Level', false, 2),
    StatValue('Independence', false, 3),
    StatValue('Sociability', false, 3),
    StatValue('Vocality', false, 2),
    StatValue('Confidence', false, 5),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 3),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(8, 'Toy Addict',
      'A playful cat obsessed with toys, games, and interactive play.',
      'Playtime is serious business.',
      8, 'Toy_Addict', 1.0, [
    StatValue('Energy Level', false, 4),
    StatValue('Playfulness', false, 5),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 3),
    StatValue('Sociability', false, 3),
    StatValue('Vocality', false, 2),
    StatValue('Confidence', false, 3),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 4),
  ]),

  CatType(9, 'Chaos Sprite',
      'A mischievous whirlwind of energy who keeps life entertaining.',
      'May cause laughter.',
      9, 'Chaos_Sprite', 1.0, [
    StatValue('Energy Level', false, 5),
    StatValue('Playfulness', false, 5),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 1),
    StatValue('Sociability', false, 4),
    StatValue('Vocality', false, 5),
    StatValue('Confidence', false, 3),
    StatValue('Sensitivity', false, 3),
    StatValue('Adaptability', false, 3),
    StatValue('Intelligence', false, 2),
  ]),

  CatType(10, 'Forever Kitten',
      'A youthful, playful cat who never quite grows out of kitten behavior.',
      'Young at heart forever.',
      10, 'Forever_Kitten', 1.0, [
    StatValue('Energy Level', false, 4),
    StatValue('Playfulness', false, 5),
    StatValue('Affection Level', false, 5),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 4),
    StatValue('Vocality', false, 3),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(11, 'Velcro Cat',
      'An extremely affectionate cat who wants to be with you at all times.',
      'Personal space is overrated.',
      11, 'Velcro_Cat', 1.0, [
    StatValue('Energy Level', false, 3),
    StatValue('Playfulness', false, 3),
    StatValue('Affection Level', false, 5),
    StatValue('Independence', false, 1),
    StatValue('Sociability', false, 5),
    StatValue('Vocality', false, 3),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(12, 'Cuddle Ambassador',
      'A friendly cat who bonds easily with people and enjoys affection.',
      'Certified hug expert.',
      12, 'Cuddle_Ambassador', 1.0, [
    StatValue('Energy Level', false, 3),
    StatValue('Playfulness', false, 3),
    StatValue('Affection Level', false, 5),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 5),
    StatValue('Vocality', false, 2),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 5),
    StatValue('Intelligence', false, 4),
  ]),

  CatType(13, 'Welcome Committee',
      'A social cat who happily greets guests and new experiences.',
      'Nice to meet you!',
      13, 'Welcome_Committee', 1.0, [
    StatValue('Energy Level', false, 4),
    StatValue('Playfulness', false, 4),
    StatValue('Affection Level', false, 4),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 5),
    StatValue('Vocality', false, 3),
    StatValue('Confidence', false, 5),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 5),
    StatValue('Intelligence', false, 4),
  ]),

  CatType(14, 'Therapy Cat',
      'An emotionally intuitive cat who provides comfort and reassurance.',
      'Always knows when you need them.',
      14, 'Therapy_Cat', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 2),
    StatValue('Affection Level', false, 5),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 4),
    StatValue('Vocality', false, 2),
    StatValue('Confidence', false, 5),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 5),
    StatValue('Intelligence', false, 4),
  ]),

  CatType(15, 'Heart Healer',
      'A deeply bonded companion who forms strong emotional connections.',
      'Love, delivered daily.',
      15, 'Heart_Healer', 1.0, [
    StatValue('Energy Level', false, 3),
    StatValue('Playfulness', false, 3),
    StatValue('Affection Level', false, 4),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 4),
    StatValue('Vocality', false, 2),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 5),
    StatValue('Intelligence', false, 4),
  ]),

  CatType(16, 'Solo Artist',
      'An independent cat who enjoys companionship on their own terms.',
      'Together, separately.',
      16, 'Solo_Artist', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 2),
    StatValue('Affection Level', false, 2),
    StatValue('Independence', false, 5),
    StatValue('Sociability', false, 2),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 3),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(17, 'Dignified Observer',
      'A calm, confident cat who prefers to watch rather than participate.',
      'Poised and unbothered.',
      17, 'Dignified_Observer', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 1),
    StatValue('Affection Level', false, 2),
    StatValue('Independence', false, 4),
    StatValue('Sociability', false, 2),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 5),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(18, 'Window Philosopher',
      'A thoughtful cat who enjoys quietly observing the world.',
      'Contemplating life, bird by bird.',
      18, 'Window_Philosopher', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 1),
    StatValue('Affection Level', false, 2),
    StatValue('Independence', false, 4),
    StatValue('Sociability', false, 1),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 3),
    StatValue('Intelligence', false, 2),
  ]),

  CatType(19, 'Private Thinker',
      'A reserved, sensitive cat who bonds slowly but deeply.',
      'Trust takes time.',
      19, 'Private_Thinker', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 1),
    StatValue('Affection Level', false, 2),
    StatValue('Independence', false, 5),
    StatValue('Sociability', false, 1),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 3),
    StatValue('Sensitivity', false, 4),
    StatValue('Adaptability', false, 2),
    StatValue('Intelligence', false, 2),
  ]),

  CatType(20, 'Gentle Hermit',
      'A shy but sweet cat who thrives in quiet, predictable environments.',
      'Soft-hearted and cautious.',
      20, 'Gentle_Hermit', 1.0, [
    StatValue('Energy Level', false, 1),
    StatValue('Playfulness', false, 1),
    StatValue('Affection Level', false, 2),
    StatValue('Independence', false, 4),
    StatValue('Sociability', false, 1),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 3),
    StatValue('Sensitivity', false, 3),
    StatValue('Adaptability', false, 2),
    StatValue('Intelligence', false, 2),
  ]),

  CatType(21, 'Drama Monarch',
      'A highly expressive cat who makes sure their feelings are known.',
      'Every moment is a performance.',
      21, 'Drama_Monarch', 1.0, [
    StatValue('Energy Level', false, 3),
    StatValue('Playfulness', false, 3),
    StatValue('Affection Level', false, 4),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 4),
    StatValue('Vocality', false, 5),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 3),
    StatValue('Adaptability', false, 3),
    StatValue('Intelligence', false, 2),
  ]),

  CatType(22, 'Opinionated Roommate',
      'A vocal cat with strong preferences and plenty to say about them.',
      'I have notes.',
      22, 'Opinionated_Roommate', 1.0, [
    StatValue('Energy Level', false, 3),
    StatValue('Playfulness', false, 3),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 3),
    StatValue('Sociability', false, 4),
    StatValue('Vocality', false, 5),
    StatValue('Confidence', false, 5),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 3),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(23, 'Soap Opera Star',
      'An affectionate but dramatic cat who feels everything intensely.',
      'Tears, cuddles, repeat.',
      23, 'Soap_Opera_Star', 1.0, [
    StatValue('Energy Level', false, 3),
    StatValue('Playfulness', false, 3),
    StatValue('Affection Level', false, 5),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 4),
    StatValue('Vocality', false, 5),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(24, 'Mood Ring Cat',
      'A sensitive cat whose emotions can change quickly with their environment.',
      'Feeling everything, always.',
      24, 'Mood_Ring_Cat', 1.0, [
    StatValue('Energy Level', false, 3),
    StatValue('Playfulness', false, 3),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 3),
    StatValue('Vocality', false, 3),
    StatValue('Confidence', false, 3),
    StatValue('Sensitivity', false, 5),
    StatValue('Adaptability', false, 2),
    StatValue('Intelligence', false, 2),
  ]),

  CatType(25, 'Attention Magnet',
      'A charismatic cat who loves being noticed and admired.',
      'Eyes on me, please.',
      25, 'Attention_Magnet', 1.0, [
    StatValue('Energy Level', false, 4),
    StatValue('Playfulness', false, 4),
    StatValue('Affection Level', false, 4),
    StatValue('Independence', false, 1),
    StatValue('Sociability', false, 5),
    StatValue('Vocality', false, 4),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 3),
  ]),

  CatType(26, 'Routine Master',
      'A structured cat who thrives on schedules and predictability.',
      'On time, every time.',
      26, 'Routine_Master', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 2),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 3),
    StatValue('Sociability', false, 3),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 5),
    StatValue('Intelligence', false, 5),
  ]),

  CatType(27, 'Puzzle Pro',
      'A clever cat who enjoys problem-solving and mental challenges.',
      'Brains before brawn.',
      27, 'Puzzle_Pro', 1.0, [
    StatValue('Energy Level', false, 3),
    StatValue('Playfulness', false, 4),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 3),
    StatValue('Sociability', false, 3),
    StatValue('Vocality', false, 2),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 2),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 5),
  ]),

  CatType(28, 'Social Learner',
      'An adaptable cat who learns quickly from people and other pets.',
      'Always picking things up.',
      28, 'Social_Learner', 1.0, [
    StatValue('Energy Level', false, 3),
    StatValue('Playfulness', false, 3),
    StatValue('Affection Level', false, 4),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 5),
    StatValue('Vocality', false, 2),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 5),
    StatValue('Intelligence', false, 5),
  ]),

  CatType(29, 'Explorer Brain',
      'A curious cat driven by discovery and new experiences.',
      'What’s over there?',
      29, 'Explorer_Brain', 1.0, [
    StatValue('Energy Level', false, 4),
    StatValue('Playfulness', false, 4),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 2),
    StatValue('Sociability', false, 3),
    StatValue('Vocality', false, 2),
    StatValue('Confidence', false, 5),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 5),
    StatValue('Intelligence', false, 4),
  ]),

  CatType(30, 'Little Professor',
      'An intelligent, observant cat who seems to understand everything.',
      'Quietly brilliant.',
      30, 'Little_Professor', 1.0, [
    StatValue('Energy Level', false, 2),
    StatValue('Playfulness', false, 2),
    StatValue('Affection Level', false, 3),
    StatValue('Independence', false, 4),
    StatValue('Sociability', false, 2),
    StatValue('Vocality', false, 1),
    StatValue('Confidence', false, 4),
    StatValue('Sensitivity', false, 1),
    StatValue('Adaptability', false, 4),
    StatValue('Intelligence', false, 5),
  ]),
];

