// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ-G6VCIKzMOD3-UPxEwDP4deZ-HlUQYo',
    appId: '1:330705375055:android:cac0ad5d0ee6531993ff3a',
    messagingSenderId: '330705375055',
    projectId: 'catapp-44885',
    authDomain: 'catapp-44885.firebaseapp.com',
    storageBucket: 'catapp-44885.appspot.com',
    measurementId: 'G-G7HM3V86C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHt2l5jQCWskt8moNjCuO4cUx3SbDBKWg',
    appId: '1:330705375055:android:cac0ad5d0ee6531993ff3a',
    messagingSenderId: '330705375055',
    projectId: 'catapp-44885',
    storageBucket: 'catapp-44885.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzeUC9Y3JPaMd4B6gqP4aa-CfDy9Jl_R8',
    appId: '1:330705375055:ios:9e146ee6eb48f08a93ff3a',
    messagingSenderId: '330705375055',
    projectId: 'catapp-44885',
    storageBucket: 'catapp-44885.appspot.com',
    androidClientId:
        '330705375055-n7e31n55fe92nlvvkdtduc7psild8mhj.apps.googleusercontent.com',
    iosClientId:
        '330705375055-5fn167olgtt5ro0ftugsqul9cbgtovjn.apps.googleusercontent.com',
    iosBundleId: 'com.gregorysiosgames.catapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzeUC9Y3JPaMd4B6gqP4aa-CfDy9Jl_R8',
    appId: '1:330705375055:ios:9e146ee6eb48f08a93ff3a',
    messagingSenderId: '330705375055',
    projectId: 'catapp-44885',
    storageBucket: 'catapp-44885.appspot.com',
    androidClientId: '330705375055-n7e31n55fe92nlvvkdtduc7psild8mhj.apps.googleusercontent.com',
    iosClientId: '330705375055-5fn167olgtt5ro0ftugsqul9cbgtovjn.apps.googleusercontent.com',
    iosBundleId: 'com.gregorysiosgames.catapp',
  );
}
